### ISSUE TITLE
coredns deployments sit in ImagePullBackOff state after cluster upgrade

### ISSUE THREAD

**Issue by Shamsun1** [Azure/aks-engine-azurestack#66]
**Describe the bug**
coredns deployments sit in an "ImagePullBackOff" state after performing a cluster upgrade. The container image referenced in the running pods is version 1.7.0 whereas the container image version for 1.21.10 is coredns:1.8.6. The pods are not being redeployed to pick up the new yaml manifest with this updated container image. Looking at the deployment yaml, "addonmanager.kubernetes.io/mode: EnsureExists" is set and looks to never upgrade the deployment as part of the upgrade. Workaround is to reapply the coredns.yaml on the master nodes.

Event from pod:
Back-off pulling image "mcr.microsoft.com/oss/kubernetes/coredns:1.7.0"

**Steps To Reproduce**
Upgrade AKS cluster from 1.20.11 to 1.21.10

**Expected behavior**
coredns deployment should reference the updated container image which is version 1.8.6

**AKS Engine version**
Upgrade from 0.67.3 to 0.70.0

**Kubernetes version**
Upgrade from 1.20.11 to 1.21.10

**Additional context**
Is this fixed in a later AKS engine version or still a bug?

**Comment by jadarsie** [comment]
Hello @Shamsun1, [this PR](https://github.com/Azure/aks-engine/pull/3067#discussion_r407717861) changed the addon manager model from "Reconcile" to "EnsureExists".

Since AKS Engine now deploys CoreDNS +v1.7.0, it should be fine to switch back to "Reconcile".

From [CoreDNS docs](https://coredns.io/plugins/reload/):

`In CoreDNS v1.6.0 and earlier any import statements are not discovered by this plugin. This means if any of these imported files changes the reload plugin is ignorant of that fact. CoreDNS v1.7.0 and later does parse the Corefile and supports detecting changes in imported files.`

A future release will include the change if no regressions are detected.
